Feature 안형석/#2
codeit-fe11-part3-team4/linkbrary pull request #13
Opened 2024-12-15 17:57 UTC by seoki0804

1.social image  기존 이미지 파일이 계속 인식이 안되어서 새로 추가하였습니다.(social 폴더)
2. page.tsx 디자인을 위한 컴포넌트 생성 및 배치
	components
	• mainLandingPage
	•Header.tsx: 헤더 컴포넌트 (로고와 로그인 버튼)
	•Footer.tsx: 푸터 컴포넌트 (소셜 아이콘 포함)
	•TopImage.tsx: 상단 이미지 섹션 컴포넌트
	•SectionImage.tsx: 여러 섹션(이미지 및 텍스트) 컴포넌트
	•Logo.tsx: 로고 컴포넌트
	•LoginButton.tsx: 로그인 버튼 컴포넌트
	
	tailwind 로 작업 중 css 적용이 되지 않아 각 컴포넌트 css 파일 만들어 적요하였음
	
3. 반응형 디자인을 적용

4. '링크 추가하기' 버튼을 클릭하면
로그인이 되어있는 경우 /share 페이지로 이동합니다.
로그인이 되지 않은 경우 /login 페이지로 이동합니다. 

이 부분은 추후 로그인 페이지 개발 코드를 보고 진행할 예정입니다.
급하게 작업을 하여서 컴포넌트별로 커밋하지 않았습니다.(죄송합니다) 기본적인 디자인은 피그마 디자인과 유사하게 구현하였습니다.
이 후 작업부터는 컴포넌트 별로, 특정 작업별로 커밋하도록 하겠습니다.

2024-12-16 02:22 UTC, Sookyeong02 reviewed
클래스네임 규칙 노션이 있으니 확인해 주세요.

2024-12-16 02:32 UTC, Jiwoo11111 requested changes
수고하셨습니다! 코드가 많은데 빠르시네용
테일윈드가 적용되지 않았던 건 제가 실수로 글로벌 CSS에서 일부 코드를 삭제했기 때문입니다 ㅠㅠ
작성해주신 CSS를 테일윈드로 변환하는 건 번거로우실 것 같아서 우선 module.css로 변경 부탁드릴게요.
테일윈드를 사용하실 거면 다음 PR에 테일윈드 관련 코드가 추가될 예정이니 그때 pull 받아서 작업해주세요
그리고 제 컴퓨터 환경에서 이미지 위치와 미디어 쿼리가 일부 깨져 보이는데 이 부분도 수정 부탁드려요!

2024-12-16 02:32 UTC, Jiwoo11111 commented on public/icons/social/google-logo.png
작은 아이콘은 svg가 좋을 거 같습니당

2024-12-16 02:32 UTC, Jiwoo11111 commented on public/icons/social/kakao-logo.png
이거도 마찬가지 입니다!

2024-12-18 02:19 UTC, Gwanhoo approved these changes
수고하셨습니다.

2024-12-19 10:06 UTC, closed without merging