Feature 김관호/#11
codeit-fe11-part3-team4/linkbrary pull request #24
Opened 2024-12-18 08:18 UTC by Gwanhoo

![image](https://github.com/user-attachments/assets/7061cb93-faff-47c2-a7b9-79706dccacf6)
![image](https://github.com/user-attachments/assets/72587631-7dd9-4386-a547-854962878162)
로그인 회원가입 페이지 만들어놨습니다 다른 기능 작업은 시작 할 예정입니다. 늦은 작업속도 죄송합니다.

2024-12-18 08:42 UTC, Jiwoo11111 requested changes
수고하셨습니다! 프로젝트 기간 아직 많이 남았으니까 천천히 해봐용

2024-12-18 08:43 UTC, Jiwoo11111 commented on src/app/login/loginPage.css
css는 module css로 변경 부탁드립니다! 각 컴포넌트 별로 고유한 클래스 네임이 생성돼서 더 관리하기 편해요! 
classname형식이랑 파일 이름만 변경하면 돼서 쉽게 수정하실 거예요

https://tori-tole.tistory.com/15

2024-12-18 08:45 UTC, Jiwoo11111 reviewed
그리고 제 컴퓨터 환경에서 로그인, 회원가입 페이지 로고가 가운데 정렬이 안 되어있는데 그 부분도 수정 부탁드립니당

2024-12-18 08:53 UTC, Sookyeong02 reviewed
전반적으로 잘 작성하신 것 같습니다!

2024-12-18 08:53 UTC, Sookyeong02 commented on src/app/login/page.tsx
> +        회원이 아니신가요? <a href="/signup">회원 가입하기</a>
a 태그를 사용하셨는데 Link 컴포넌트를 사용하는 것이 더 일관성 있을 것 같습니다.

2024-12-18 12:58 UTC, Jiwoo11111 reviewed
그리고 머지 main 말고 develop으로 변경해주세요!!

2024-12-24 06:06 UTC, Sookyeong02 approved these changes

2024-12-26 12:48 UTC, closed without merging