Feature 김관호/#25
codeit-fe11-part3-team4/linkbrary pull request #35
Opened 2024-12-22 05:29 UTC by Gwanhoo

로그인 및 회원가입 페이지에 loginUser 함수와 signUpUser 함수 구현을 했습니다. teamId를 고정된 값을 써도 되는지 잘 몰라서 
const response = await fetch(`/4/auth/sign-up` 라고 쓰긴했습니다 참고해주세요.

2024-12-23 03:30 UTC, Jiwoo11111 reviewed
관호님!! 머지되는 브랜치 main 말고 develop으로 변경해주세요!

2024-12-23 03:44 UTC, Jiwoo11111 requested changes
관호님!! 머지되는 브랜치 main 말고 develop으로 변경해주세요!

2024-12-23 03:44 UTC, Jiwoo11111 commented on src/app/login/loginPage.css
css 모듈css로 변경해주세요

2024-12-23 03:44 UTC, Jiwoo11111 commented on src/app/login/page.tsx
> +      });
이 컴포넌트에서 api를 호출하는 코드인 거 같은데
api.ts파일에서 이미 postSignIn으로 로그인 처리할 수 있는 함수가 있으니 그걸 사용해주세요

2024-12-23 03:44 UTC, Jiwoo11111 commented on src/app/signup/page.tsx
> +
이 코드드 마찬가지 입니다 
api.ts에 postSignup함수를 사용해주세요

2024-12-23 03:44 UTC, Jiwoo11111 commented on src/app/signup/signupPage.css
마찬가지로 css파일 모듈로 변경해주세요 저번 pr에 링크랑 같이 리뷰 남겼으니 그걸 참고해주세요

2024-12-23 03:58 UTC, Jiwoo11111 commented on src/app/login/page.tsx
> +  const handleSubmit = (e: React.FormEvent) => {
이미 utils/AutoContext.tsx파일에서 accessToken이랑 user상태를 전역적으로 관리하고 있습니다.
useAuth 함수를 사용해서 상태와 토큰을 관리하는 방식으로 수정해주세요

2024-12-23 03:59 UTC, Jiwoo11111 reviewed
>> 로그인 및 회원가입 페이지에 loginUser 함수와 signUpUser 함수 구현을 했습니다. teamId를 고정된 값을 써도 되는지 잘 몰라서
const response = await fetch(/4/auth/sign-up 라고 쓰긴했습니다 참고해주세요.

api.ts에 있는 함수들 사용하면 따로 쿼리 작성하지 않아도 됩니다

2024-12-23 10:22 UTC, Jiwoo11111 approved these changes

2024-12-24 06:06 UTC, Sookyeong02 approved these changes

2024-12-24 06:06 UTC, merged