feet: 폴더 구조 및 Tailwind CSS
codeit-fe11-part3-team4/linkbrary pull request #7
Opened 2024-12-13 13:41 UTC by Sookyeong02

## 설명
폴더 구조 및 Tailwind CSS

## 필수 기능
- [ ] App Routing
- [ ] Tailwind CSS

## 추가적인 기능
- [ ] images, icons 추가

2024-12-13 14:49 UTC, Jiwoo11111 requested changes
이미지까지 넣어주셨네요 수고하셨습니다! 밑에 내용들 수정해주세용

2024-12-13 15:10 UTC, Jiwoo11111 commented on src/assets/icons/facebook.svg
앱 라우터에서는 이미지 최적화 기능을 제공하고 있기에 이런 작은 아이콘 같은 정적 파일은 public/ 폴더에 넣는 걸 권장하고 있습니당
작은 아이콘들은 public/icon 폴더에 넣어주세요
노션에 폴더 구조 확인해주세요!

2024-12-13 15:10 UTC, Jiwoo11111 commented on src/assets/icons/logo.svg
로고도 마찬가지입니다!

2024-12-13 15:10 UTC, Jiwoo11111 commented on src/assets/images/logo.png
png 형식 로고는 필요 없어 보입니당

2024-12-13 15:10 UTC, Jiwoo11111 commented on src/styles/globals.css
> +  font-family: "Pretendard-Regular", sans-serif;
폰트는 어차피 전역에 들어가는 거니까 *태그에 추가해보면 어떨까요??

2024-12-14 00:08 UTC, Gwanhoo approved these changes
감사합니다.

2024-12-14 00:19 UTC, Jiwoo11111 approved these changes

2024-12-14 00:23 UTC, merged